name: "PR GPT Summary"
description: "PR의 diff를 요약해 한국어 리뷰 코멘트를 자동으로 남기는 GitHub Action"

inputs:
  token:
    description: "GitHub 토큰(예: secrets.GITHUB_TOKEN)"
    required: true
  openai_api_key:
    description: "OpenAI API Key(예: secrets.OPENAI_API_KEY)"
    required: true
  model:
    description: "OpenAI 모델 이름 (기본값: gpt-4o)"
    default: "gpt-4o"
    required: false
  system_prompt:
    description: |
      시스템 프롬프트(선택).  
      입력하지 않으면 기본 한국어 프롬프트를 사용합니다.
    required: false
  template:
    description: |
      추가 지시 템플릿(선택).  
      {{diff}}, {{file_list}} 플레이스홀더를 쓰거나 비워 두면 자동으로 삽입됩니다.
    required: false

runs:
  using: "node16"
  main: "index.js"
