name: 'PR GPT Summary'
description: 'PR에 ChatGPT 기반 요약 코멘트를 자동으로 답니다.'

branding:
  icon: "message-square"
  color: "yellow"

inputs:
  token:
    description: "GitHub token"
    required: true
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  model:
    description: "OpenAI 모델명 (예: gpt-4o, gpt-3.5-turbo)"
    required: true
    default: "gpt-4.1-nano"
  template:
    description: "PR 요약 양식 (항목명/순서/설명 포함, 반드시 한국어로 작성)"
    required: true
    default: |
      1. 수정한 파일 목록
      {{파일목록}}

      2. PR 수정 내용 전체 요약 정리

      3. 파일별 수정 사항 정리

      4. 리뷰 순서 추천

runs:
  using: "node16"
  main: "dist/index.js"
